# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - mlinprodobli

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true

    - name: Checkout LFS objects
      run: git lfs checkout model/model.h5

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://index.docker.io/v1/
        username: ${{ secrets.AzureAppService_ContainerUsername_05b949109468462da90792cfe5cae2e3 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_c554156440a5416e9d0b0b9d5f02b110 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05b949109468462da90792cfe5cae2e3 }}/inference:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'mlinprodobli'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_260c0b014652426d874e37f39c74ed40 }}
        images: 'index.docker.io/${{ secrets.AzureAppService_ContainerUsername_05b949109468462da90792cfe5cae2e3 }}/inference:${{ github.sha }}'
